/**
 * Scenario presets for workflow simulator
 */

export const scenarios = {
  'photos-required-normal': {
    name: 'Photos Required - Normal Flow',
    description: 'Start fresh - click "Request Quote" to begin (estimate will auto-send)',
    state: {
      workflow: {
        status: null,
        currentStep: 0,
        requestedAt: null,
        reviewedAt: null,
        acceptedAt: null,
        bookedAt: null,
        paidAt: null,
      },
      quote: {
        status: null,
        statusLabel: null,
        number: null,
        acceptedAt: null,
        sentAt: null,
        sendCount: 0,
        acceptance_enabled: false,
        enabled_at: null,
        enabled_by: null,
        photos_required: true,
        approval_requested: false, // NEW
      },
      photos: {
        submission_status: null,
        submitted_at: null,
        total: 0,
        uploaded: 0,
        items: [],
        reviewed: false,
        reviewed_at: null,
        reviewed_by: null,
      },
      invoice: {
        id: null,
        number: null,
        status: null,
        total: 0,
        paid: 0,
        balance: 0,
        created_at: null,
      },
      account: {
        status: 'pending',
        inviteToken: null,
        portalUrl: null,
      },
    },
  },
  'photos-required-under-review': {
    name: 'Photos Required - Under Review',
    description: 'Customer has submitted photos, waiting for admin review and approval',
    state: {
      workflow: {
        status: 'under_review', // NEW: Changed from 'reviewing' to 'under_review'
        currentStep: 2,
        requestedAt: '2025-01-15 10:00:00',
        reviewedAt: null,
        acceptedAt: null,
        bookedAt: null,
        paidAt: null,
      },
      quote: {
        status: 'sent',
        statusLabel: 'Sent',
        number: 'EST-123',
        acceptedAt: null,
        sentAt: '2025-01-15 10:00:00',
        sendCount: 1,
        acceptance_enabled: false,
        enabled_at: null,
        enabled_by: null,
        photos_required: true,
        approval_requested: true, // NEW: Customer requested approval
      },
      photos: {
        submission_status: 'submitted',
        submitted_at: '2025-01-15 10:35:00',
        total: 7,
        uploaded: 7,
        items: Array(7).fill(null).map((_, i) => ({ id: i + 1, product: `Product ${i + 1}`, count: 1 })),
        reviewed: false,
        reviewed_at: null,
        reviewed_by: null,
      },
      invoice: {
        id: null,
        number: null,
        status: null,
        total: 0,
        paid: 0,
        balance: 0,
        created_at: null,
      },
      account: {
        status: 'active',
        inviteToken: 'abc123',
        portalUrl: 'http://localhost:3000/portal?estimateId=est-123&inviteToken=abc123',
      },
    },
  },
  'photos-required-changes': {
    name: 'Photos Required - Changes Requested',
    description: 'Customer submitted photos, admin reviewed and requested changes/more photos. Customer can resubmit.',
    state: {
      workflow: {
        status: 'under_review', // NEW: Changed from 'reviewed' to 'under_review'
        currentStep: 2,
        requestedAt: '2025-01-15 10:00:00',
        reviewedAt: '2025-01-15 11:00:00',
        acceptedAt: null,
        bookedAt: null,
        paidAt: null,
      },
      quote: {
        status: 'sent',
        statusLabel: 'Sent',
        number: 'EST-123',
        acceptedAt: null,
        sentAt: '2025-01-15 10:00:00',
        sendCount: 1,
        acceptance_enabled: false, // NOT enabled because changes requested
        enabled_at: null,
        enabled_by: null,
        photos_required: true,
      },
      photos: {
        submission_status: 'submitted', // Photos were submitted
        submitted_at: '2025-01-15 10:35:00',
        total: 5,
        uploaded: 5,
        items: Array(5).fill(null).map((_, i) => ({ id: i + 1, product: `Product ${i + 1}`, count: 1 })),
        reviewed: true, // Admin reviewed them
        reviewed_at: '2025-01-15 11:00:00', // Admin reviewed at this time
        reviewed_by: 'admin-1', // Admin who reviewed
        // Note: acceptance_enabled is false, meaning admin reviewed but requested changes
      },
      invoice: {
        id: null,
        number: null,
        status: null,
        total: 0,
        paid: 0,
        balance: 0,
        created_at: null,
      },
      account: {
        status: 'active',
        inviteToken: 'abc123',
        portalUrl: 'http://localhost:3000/portal?estimateId=est-123&inviteToken=abc123',
      },
    },
  },
  'no-photos-required': {
    name: 'No Photos Required',
    description: 'Admin can enable acceptance immediately after sending estimate',
    state: {
      workflow: {
        status: 'sent', // NEW: Changed from 'reviewing' to 'sent'
        currentStep: 2,
        requestedAt: '2025-01-15 10:00:00',
        reviewedAt: null,
        acceptedAt: null,
        bookedAt: null,
        paidAt: null,
      },
      quote: {
        status: 'sent',
        statusLabel: 'Sent',
        number: 'EST-123',
        acceptedAt: null,
        sentAt: '2025-01-15 10:00:00',
        sendCount: 1,
        acceptance_enabled: false,
        enabled_at: null,
        enabled_by: null,
        photos_required: false,
        approval_requested: false, // NEW
      },
      photos: {
        submission_status: null,
        submitted_at: null,
        total: 0,
        uploaded: 0,
        items: [],
        reviewed: false,
        reviewed_at: null,
        reviewed_by: null,
      },
      invoice: {
        id: null,
        number: null,
        status: null,
        total: 0,
        paid: 0,
        balance: 0,
        created_at: null,
      },
      account: {
        status: 'active',
        inviteToken: 'abc123',
        portalUrl: 'http://localhost:3000/portal?estimateId=est-123&inviteToken=abc123',
      },
    },
  },
  'partial-payment': {
    name: 'Partial Payment Flow',
    description: 'Customer accepts, pays partial amount',
    state: {
      workflow: {
        status: 'accepted',
        currentStep: 3,
        requestedAt: '2025-01-15 10:00:00',
        reviewedAt: '2025-01-15 10:40:00',
        acceptedAt: '2025-01-15 11:00:00',
        bookedAt: null,
        paidAt: null,
      },
      quote: {
        status: 'accepted',
        statusLabel: 'Accepted',
        number: 'EST-123',
        acceptedAt: '2025-01-15 11:00:00',
        sentAt: '2025-01-15 10:00:00',
        sendCount: 1,
        acceptance_enabled: true,
        enabled_at: '2025-01-15 10:40:00',
        enabled_by: 1,
        photos_required: true,
      },
      photos: {
        submission_status: 'submitted',
        submitted_at: '2025-01-15 10:35:00',
        total: 7,
        uploaded: 7,
        items: Array(7).fill(null).map((_, i) => ({ id: i + 1, product: `Product ${i + 1}`, count: 1 })),
        reviewed: true,
        reviewed_at: '2025-01-15 10:40:00',
        reviewed_by: 1,
      },
      invoice: {
        id: 'inv-123',
        number: 'INV-456',
        status: 'partial', // Updated to use 'partial' for consistency with production
        total: 650,
        paid: 200,
        balance: 450,
        created_at: '2025-01-15 11:00:00',
      },
      account: {
        status: 'active',
        inviteToken: 'abc123',
        portalUrl: 'http://localhost:3000/portal?estimateId=est-123&inviteToken=abc123',
      },
    },
  },
  'rejected': {
    name: 'Rejected Estimate',
    description: 'Customer rejects the estimate',
    state: {
      workflow: {
        status: 'sent', // NEW: Changed from 'reviewing' to 'sent'
        currentStep: 2,
        requestedAt: '2025-01-15 10:00:00',
        reviewedAt: null,
        acceptedAt: null,
        bookedAt: null,
        paidAt: null,
      },
      quote: {
        status: 'rejected',
        statusLabel: 'Rejected',
        number: 'EST-123',
        acceptedAt: null,
        sentAt: '2025-01-15 10:00:00',
        sendCount: 1,
        acceptance_enabled: false,
        enabled_at: null,
        enabled_by: null,
        photos_required: true,
        approval_requested: false, // NEW
      },
      photos: {
        submission_status: null,
        submitted_at: null,
        total: 0,
        uploaded: 0,
        items: [],
        reviewed: false,
        reviewed_at: null,
        reviewed_by: null,
      },
      invoice: {
        id: null,
        number: null,
        status: null,
        total: 0,
        paid: 0,
        balance: 0,
        created_at: null,
      },
      account: {
        status: 'active',
        inviteToken: 'abc123',
        portalUrl: 'http://localhost:3000/portal?estimateId=est-123&inviteToken=abc123',
      },
    },
  },
  'fresh': {
    name: 'Custom (Start Fresh)',
    description: 'Start with empty state',
    state: {
      workflow: {
        status: null,
        currentStep: 0,
        requestedAt: null,
        reviewedAt: null,
        acceptedAt: null,
        bookedAt: null,
        paidAt: null,
      },
      quote: {
        status: null,
        statusLabel: null,
        number: null,
        acceptedAt: null,
        sentAt: null,
        sendCount: 0,
        acceptance_enabled: false,
        enabled_at: null,
        enabled_by: null,
        photos_required: null,
        approval_requested: false, // NEW
      },
      photos: {
        submission_status: null,
        submitted_at: null,
        total: 0,
        uploaded: 0,
        items: [],
        reviewed: false,
        reviewed_at: null,
        reviewed_by: null,
      },
      invoice: {
        id: null,
        number: null,
        status: null,
        total: 0,
        paid: 0,
        balance: 0,
        created_at: null,
      },
      account: {
        status: 'pending',
        inviteToken: null,
        portalUrl: null,
      },
    },
  },
};

export const getInitialState = () => ({
  estimateId: 'sample-est-123',
  locationId: 'aLTXtdwNknfmEFo3WBIX',
  ...scenarios['photos-required-normal'].state,
});
